### ISSUE TITLE
Is it safe to put it in git?

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeoscontracts#1]
https://github.com/FreeosDAO/freeoscontracts/blob/master/freeos/eos.pwd
 it seems some password.

Not sure, but asking is it safe to put in git?

**Comment by tommccann777** [comment]
If it's a password to a development account then it's ok, bit would prefer
for it not to be there.

Tom

**Comment by tommccann777** [comment]
I will remove that password file.

Tom

**Comment by tommccann777** [comment]
The file has been removed
