### ISSUE TITLE
Was able to claim before staking

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeoscontracts#11]
Iteration 4 account vivvestin (type e) 
Was able to claim before staking 20 XPR for iteration 4 .
getuser action
>> account: vivvestin, registered: 1614550573, type: e, stake: 10.0000 XPR, staked-on: 1614558237, XPR: 39.0000 XPR, liquid: 110.0000 FREEOS, vested: 90.0000 FREEOS, airkey: 0 AIRKEY, iteration: 4, claimed: false
check usercount
"""usercount"": 9,
      ""claimevents"": 7,
      ""unvestpercent"": 0,
      ""unvestpercentiteration"": 1,
      ""iteration"": 4,
      ""failsafecounter"": 0"
check stake requirement for type = e
      ""threshold"": 5,
      ""requirement_a"": ""0.0000 XPR"",
      ""requirement_b"": ""0.0000 XPR"",
      ""requirement_c"": ""0.0000 XPR"",
      ""requirement_d"": ""10.0000 XPR"",
      ""requirement_e"": ""20.0000 XPR"",
      ""requirement_u"": ""0.0000 XPR"",
      ""requirement_v"": ""0.0000 XPR"",
      ""requirement_w"": ""0.0000 XPR"",
      ""requirement_x"": ""0.0000 XPR"",
      ""requirement_y"": ""0.0000 XPR""

Try to claim for iteration 4 without staking 20 XPR (-ve testing) expect claim to be unsuccessful but was able to claim:
gitpod /workspace $ proton push action freeos333333 claim '["vivvestin"]' -p vivvestin@active
executed transaction: 4f6631a354e85b94c21a3d78fe48c38b6e51a1a1902a0186dd258003f8fabd41  104 bytes  428 us
#  freeos333333 <= freeos333333::claim          {"user":"vivvestin"}
>> vivvestin claimed 158.0000 FREEOS and vested 17.0000 FREEOS for iteration 4
#  freeos333333 <= freeos333333::issue          {"to":"freeos333333","quantity":"6108.0000 FREEOS","memo":"claim by vivvestin"}
#  freeos333333 <= freeos333333::transfer       {"from":"freeos333333","to":"vivvestin","quantity":"158.0000 FREEOS","memo":"claim by vivvestin"}
#     vivvestin <= freeos333333::transfer       {"from":"freeos333333","to":"vivvestin","quantity":"158.0000 FREEOS","memo":"claim by vivvestin"}
#  freeos333333 <= freeos333333::transfer       {"from":"freeos333333","to":"freeosdivide","quantity":"5950.0000 FREEOS","memo":"claim by vivvestin"...
#  freeosdivide <= freeos333333::transfer       {"from":"freeos333333","to":"freeosdivide","quantity":"5950.0000 FREEOS","memo":"claim by vivvestin"...

Check state of user again. XPR balance still 39 cos Ii havent staked before claiming.. 
gitpod /workspace $ proton push action freeos333333 getuser '["vivvestin"]' -p vivvestin@active
executed transaction: 02a78fb9440f5a67b20657b22470a9f7edaf1a49808d1860fd8ca54a2cfdc846  104 bytes  293 us
#  freeos333333 <= freeos333333::getuser        {"user":"vivvestin"}
>> account: vivvestin, registered: 1614550573, type: e, stake: 10.0000 XPR, staked-on: 1614558237, XPR: 39.0000 XPR, liquid: 268.0000 FREEOS, vested: 107.0000 FREEOS, airkey: 0 AIRKEY, iteration: 4, claimed: true

**Comment by tommccann777** [comment]
This is a misunderstanding. The user only has to stake once and then they can claim every iteration.
