### ISSUE TITLE
Question about ticker - seems uninitialised

### ISSUE THREAD

**Issue by shahidnz** [FreeosDAO/freeoscontracts#2]
$FREEOS_TICKER is used without initialising or exporting

it either depends on env of there is a risk that it remains NULL

Please check
https://github.com/FreeosDAO/freeoscontracts/blob/master/freeos/freeosticker.sh

**Comment by tommccann777** [comment]
The impact of $FREEOS_TICKER not being initialised is that the job would
fail. That's ok. It just means we have to keep our eye on whether it is
running or not.

Tom

**Comment by tommccann777** [comment]
$FREEOS_TICKER is deliberately not set within the shell script.
