### ISSUE TITLE
Unknown key : freeos333333 and freeostokens

### ISSUE THREAD

**Issue by judytan21** [FreeosDAO/freeoscontracts#4]
18/2/21 3:28pm - emailed Tom regarding the following issue. 
While testing, the following cleos commands failed with errors as shown below:
gitpod /workspace $ cleos push action freeostokens reguser '["vannavestin","e"]' -p vannavestin@active
error 2021-02-18T02:20:49.270 cleos     main.cpp:3940                 main                 ] Failed with error: unspecified (0)
unknown key (eosio::chain::name): freeostokens

gitpod /workspace $ cleos push action freeos333333 getuser '["vannavestin"]' -p vannavestin@active
error 2021-02-18T02:23:38.734 cleos     main.cpp:3940                 main                 ] Failed with error: unspecified (0)
unknown key (eosio::chain::name): freeos333333

gitpod /workspace $ cleos push action freeos333333 getuser '["vannavestin"]' -p freeos3333333@active
error 2021-02-18T02:24:50.169 cleos     main.cpp:3940                 main                 ] Failed with error: unspecified (0)
unknown key (eosio::chain::name): freeos333333

**Comment by judytan21** [comment]
18/2/21 4:22pm
Got the same error when running Claim action.
gitpod /workspace $ cleos push action freeos333333 claim '["vannavestin"]' -p vannavestin3@active
error 2021-02-18T03:17:03.940 cleos     main.cpp:3940                 main                 ] Failed with error: unspecified (0)
unknown key (eosio::chain::name): freeos333333

**Comment by tommccann777** [comment]
@judytan21  This is because you are using cleos without the -u parameter specified. I will close this issue.
